// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get settingsTitle => 'Settings';

  @override
  String get passwordStrength => 'Password Strength';

  @override
  String get language => 'Language';

  @override
  String get strong => 'Strong';

  @override
  String get medium => 'Medium';

  @override
  String get weak => 'Weak';

  @override
  String get welcomeTitle => 'Welcome to PwBox';

  @override
  String get createDatabase => 'Create Database';

  @override
  String get openDatabase => 'Open Database';

  @override
  String get unlockDatabaseTitle => 'Unlock Database';

  @override
  String get unlockingDatabase => 'Loading the database...';

  @override
  String get masterPassword => 'Master Password';

  @override
  String get unlockButton => 'Unlock';

  @override
  String get switchDatabaseButton => 'Switch Database';

  @override
  String get enter2faCodeHint =>
      'Please enter the 6-digit verification code generated by your authenticator app.';

  @override
  String get passwordCannotBeEmpty => 'Password cannot be empty.';

  @override
  String get failedToOpenDatabase => 'Failed to open database: Corrupted file.';

  @override
  String get invalidPasswordError => 'Invalid password.';

  @override
  String get selectDatabaseFile => 'Select a database file';

  @override
  String get homeTitle => 'PwBox - Your Secure Vault';

  @override
  String get lockDatabaseTooltip => 'Lock Database';

  @override
  String get settingsTooltip => 'Settings';

  @override
  String get newGroupDialogTitle => 'New Group';

  @override
  String get renameGroupDialogTitle => 'Rename Group';

  @override
  String get groupNameHint => 'Group Name';

  @override
  String get databaseNameHint => 'Database Name';

  @override
  String get cancelButton => 'Cancel';

  @override
  String get saveButton => 'Save';

  @override
  String get addNewEntryButton => 'Add New Entry';

  @override
  String get noGroupSelectedErrorTitle => 'No Group Selected';

  @override
  String get noGroupSelectedErrorContent =>
      'Please select a group before adding a new entry.';

  @override
  String get deleteEntryConfirmationTitle => 'Delete Entry?';

  @override
  String deleteEntryConfirmationContent(Object entryTitle) {
    return 'Are you sure you want to delete \"$entryTitle\"? This action cannot be undone.';
  }

  @override
  String get deleteGroupConfirmationTitle => 'Delete Group?';

  @override
  String deleteGroupConfirmationContent(Object groupName) {
    return 'Are you sure you want to delete \"$groupName\"? This action cannot be undone.';
  }

  @override
  String get cannotDeleteGroupErrorTitle => 'Cannot Delete Group';

  @override
  String get cannotDeleteGroupErrorContent =>
      'This group is not empty. Please move or delete all entries first.';

  @override
  String get cannotDeleteGroupWithSubgroupsErrorContent =>
      'This group contains subgroups. Please move or delete all subgroups first.';

  @override
  String get okButton => 'OK';

  @override
  String get generalGroupName => 'General';

  @override
  String get searchEntries => 'Search Entries';

  @override
  String get noSearchResults => 'No search results found.';

  @override
  String get emptyGroup => 'This group is empty.';

  @override
  String get addEntryHint =>
      'Click the \'+\' button in the top right to add a new entry.';

  @override
  String get collapseGroup => 'Collapse Group';

  @override
  String get expandGroup => 'Expand Group';

  @override
  String get hidePassword => 'Hide Password';

  @override
  String get showPassword => 'Show Password';

  @override
  String get copyUsernameTooltip => 'Copy Username';

  @override
  String get copyPasswordTooltip => 'Copy Password';

  @override
  String get editButton => 'Edit';

  @override
  String get deleteButton => 'Delete';

  @override
  String get usernameCopied => 'Username copied to clipboard!';

  @override
  String get passwordCopied => 'Password copied to clipboard!';

  @override
  String get urlCopied => 'URL copied to clipboard!';

  @override
  String get copyUrlTooltip => 'Copy URL';

  @override
  String get addEntryTitle => 'Add New Entry';

  @override
  String get editEntryTitle => 'Edit Entry';

  @override
  String get titleLabel => 'Title';

  @override
  String get titleEmptyError => 'Title cannot be empty';

  @override
  String get usernameLabel => 'Username';

  @override
  String get passwordLabel => 'Password';

  @override
  String get urlLabel => 'URL';

  @override
  String get attachmentsLabel => 'Attachments';

  @override
  String get addAttachmentButton => 'Add Attachment';

  @override
  String get saveEntryButton => 'Save';

  @override
  String get noAttachmentsYet => 'No attachments yet.';

  @override
  String previewNotSupported(Object fileName) {
    return 'Preview for this file type is not supported.\n\n$fileName';
  }

  @override
  String get closeButton => 'Close';

  @override
  String get generatePasswordTooltip => 'Generate Password';

  @override
  String get generalSettingsTab => 'General';

  @override
  String get securitySettingsTab => 'Security';

  @override
  String get aboutSettingsTab => 'About';

  @override
  String get appVersion => 'App Version';

  @override
  String get databasePath => 'Database Path';

  @override
  String get newDatabaseEncryptionStrength =>
      'New Database Encryption Strength';

  @override
  String get higherIterations =>
      'Higher iterations are more secure but slower to open.';

  @override
  String get fast => 'Fast';

  @override
  String get balanced => 'Balanced';

  @override
  String get paranoid => 'Paranoid';

  @override
  String get changeMasterPassword => 'Change Master Password';

  @override
  String get notYetImplemented => 'Not yet implemented';

  @override
  String get aboutPwBox => 'About PwBox';

  @override
  String get aboutPwBoxDescription =>
      'PwBox is a Absolutely safe and secure password manager for cross-platform compatibility.';

  @override
  String get author => 'Author';

  @override
  String get createDatabaseTitle => 'Create New Database';

  @override
  String get creatingDatabaseMessage =>
      'Creating secure database...\nThis is a one-time operation and may take a minute.';

  @override
  String get masterPasswordLabel => 'Master Password';

  @override
  String get encryptionStrengthLabel => 'Encryption Strength';

  @override
  String get createAndSaveButton => 'Create and Save';

  @override
  String get nextButton => 'Next';

  @override
  String get passwordEmptyError => 'Password cannot be empty.';

  @override
  String get autoLockDatabase => 'Auto-lock database';

  @override
  String get never => 'Never';

  @override
  String get minute => 'minute(s)';

  @override
  String get oneMinute => '1 minute';

  @override
  String get fiveMinutes => '5 minutes';

  @override
  String get fifteenMinutes => '15 minutes';

  @override
  String get openLocalDatabase => 'Open Local Database';

  @override
  String get openNetworkDatabase => 'Open Network Database';

  @override
  String get masterPasswordChangedSuccessfully =>
      'Master password changed successfully!';

  @override
  String get invalidCurrentPassword => 'Invalid current password.';

  @override
  String get currentMasterPassword => 'Current Master Password';

  @override
  String get newMasterPassword => 'New Master Password';

  @override
  String get confirmNewMasterPassword => 'Confirm New Master Password';

  @override
  String get passwordsDoNotMatch => 'Passwords do not match';

  @override
  String get groups => 'Groups';

  @override
  String get addGroup => 'Add Group';

  @override
  String get addSubgroup => 'Add Subgroup';

  @override
  String get renameGroup => 'Rename Group';

  @override
  String get deleteGroup => 'Delete Group';

  @override
  String get changeButton => 'Change';

  @override
  String get passwordStrengthNone => 'No password';

  @override
  String get passwordStrengthWeak => 'Weak';

  @override
  String get passwordStrengthMedium => 'Medium';

  @override
  String get passwordStrengthStrong => 'Strong';

  @override
  String get downloadAttachmentTooltip => 'Download';

  @override
  String get removeAttachmentTooltip => 'Remove';

  @override
  String get saveAttachmentAs => 'Save Attachment As';

  @override
  String attachmentSavedSuccessfully(Object fileName) {
    return 'Attachment \"$fileName\" saved successfully!';
  }

  @override
  String failedToSaveAttachment(Object error, Object fileName) {
    return 'Failed to save attachment \"$fileName\": $error';
  }

  @override
  String get enableAutoBackup => 'Enable Automatic Backup';

  @override
  String get settingsSaved => 'Settings saved.';

  @override
  String get theme => 'Theme';

  @override
  String get themeSystem => 'System';

  @override
  String get themeLight => 'Light';

  @override
  String get themeDark => 'Dark';

  @override
  String get languageEnglish => 'English';

  @override
  String get languageChinese => 'Chinese';

  @override
  String get passwordGeneratorIncludeUppercase => 'Include Uppercase (A-Z)';

  @override
  String get passwordGeneratorIncludeLowercase => 'Include Lowercase (a-z)';

  @override
  String get passwordGeneratorIncludeNumeric => 'Include Numbers (0-9)';

  @override
  String get passwordGeneratorIncludeSpecial =>
      'Include Special Characters (!@#...)';

  @override
  String get appearanceSettings => 'Appearance Settings';

  @override
  String get backupSettings => 'Backup Settings';

  @override
  String get databaseSettings => 'Database Settings';

  @override
  String get securityFeatures => 'Security Features';

  @override
  String get addSubGroup => 'Add Subgroup';

  @override
  String get enable2fa => 'Enable Two-Factor Authentication';

  @override
  String get scanQrCodeWithAuthenticator =>
      'Scan the QR code with your authenticator app.';

  @override
  String get orEnterSecretManually => 'Or enter this secret manually:';

  @override
  String get enter2faCode => 'Enter 2FA Code';

  @override
  String get verifyAndSaveButton => 'Verify and Save';

  @override
  String get invalid2faCode => 'Invalid 2FA code.';

  @override
  String get disable2fa => 'Disable Two-Factor Authentication';

  @override
  String get disable2faConfirmation =>
      'Are you sure you want to disable two-factor authentication? You will no longer be prompted for a 2FA code when unlocking your database.';

  @override
  String get disableButton => 'Disable';

  @override
  String get twoFactorAuthDisabled =>
      'Two-factor authentication has been disabled.';

  @override
  String get twoFactorAuthRequired =>
      'Two-factor authentication is required to unlock this database.';

  @override
  String get verifyButton => 'Verify';

  @override
  String get fontSize => 'Font Size';

  @override
  String get recycleBin => 'Recycle';

  @override
  String get emptyRecycleBin => 'Empty Recycle Bin';

  @override
  String get emptyRecycleBinConfirmation =>
      'Are you sure you want to permanently delete all items in the recycle bin? This action cannot be undone.';

  @override
  String get recycleBinIsEmpty => 'Recycle bin is empty.';

  @override
  String get restore => 'Restore';

  @override
  String get permanentlyDelete => 'Permanently Delete';

  @override
  String get permanentlyDeleteConfirmation =>
      'Are you sure you want to permanently delete this item? This action cannot be undone.';

  @override
  String get recycleBinRetention => 'Recycle Bin Retention';

  @override
  String get sevenDays => '7 Days';

  @override
  String get thirtyDays => '30 Days';

  @override
  String get ninetyDays => '90 Days';

  @override
  String get oneHundredEightyDays => '180 Days';

  @override
  String get threeHundredSixtyFiveDays => '365 Days';

  @override
  String get saving => 'Saving...';

  @override
  String get openButton => 'Open';

  @override
  String get unlockDatabase => 'Unlock Database';

  @override
  String get switchDatabase => 'Switch Database';

  @override
  String get selectDatabaseFolder => 'Select a folder to save your database';

  @override
  String get networkDatabaseNotImplemented =>
      'Network database functionality is not yet implemented.';

  @override
  String get basicInformation => 'Basic Information';

  @override
  String get groupLabel => 'Group';

  @override
  String get notesLabel => 'Notes';

  @override
  String get generatePasswordButton => 'Generate Password';

  @override
  String get copyPasswordButton => 'Copy Password';

  @override
  String get generatedPassword => 'Generated Password';

  @override
  String get passwordOptions => 'Password Options';

  @override
  String get passwordLength => 'Password Length';

  @override
  String get generateButton => 'Generate';

  @override
  String get useThisPasswordButton => 'Use This Password';

  @override
  String get deletedAt => 'Deleted At';

  @override
  String get lockDatabaseShortcut => 'Lock Database Shortcut';

  @override
  String get shortcutNotSet => 'Not set';

  @override
  String get pressShortcutToRecord => 'Press shortcut to record';

  @override
  String get shortcutRecording => 'Recording shortcut... Press Esc to cancel';

  @override
  String get enter6DigitCode => 'Enter 6-digit code';

  @override
  String errorCreatingDatabase(Object error) {
    return 'Error creating database: $error';
  }

  @override
  String get selectDatabaseDialogTitle =>
      'Select your database file (database.pdbw)';

  @override
  String unexpectedErrorWithMessage(Object error) {
    return 'An unexpected error occurred: $error';
  }

  @override
  String get attachmentDataNotFound => 'Data for this attachment not found.';

  @override
  String errorInitializingScreen(Object error) {
    return 'Error initializing screen: $error';
  }

  @override
  String get refreshButton => 'Refresh';

  @override
  String get entrySavedSuccessfully => 'Entry saved successfully';

  @override
  String failedToSaveEntry(String error) {
    return 'Failed to save entry: $error';
  }

  @override
  String get backupCreatedSuccessfully => 'Initial backup created successfully';

  @override
  String backupFailed(String error) {
    return 'Backup failed: $error';
  }

  @override
  String lastBackupLabel(String datetime) {
    return 'Last: $datetime';
  }

  @override
  String get confirmPassword => 'Confirm Password';

  @override
  String get databaseNameEmptyHint =>
      'Leave empty to use default name \"pwbox\"';

  @override
  String get invalidDatabaseName =>
      'Database name contains invalid characters. Please avoid using <>:\"/\\|?*';

  @override
  String get databaseNameCannotStartWithDot =>
      'Database name cannot start with a dot.';

  @override
  String get clearSearch => 'Clear Search';

  @override
  String get errorTitle => 'Error';

  @override
  String get unexpectedError => 'An unexpected error occurred.';

  @override
  String errorLoadingAttachment(Object error) {
    return 'Error loading attachment: $error';
  }

  @override
  String errorLoadingData(Object error) {
    return 'Error loading data: $error';
  }

  @override
  String get aboutPwBoxLongDescription =>
      'PwBox is a free, open-source, cross-platform password manager that helps you securely store and manage all your passwords.';

  @override
  String failedToChangePassword(Object error) {
    return 'Failed to change master password: $error';
  }

  @override
  String get settings => 'Settings';

  @override
  String get groupNotFound => 'N/A';

  @override
  String deletedAtLabel(Object date) {
    return 'Deleted At: $date';
  }

  @override
  String get shortcutCtrl => 'Ctrl';

  @override
  String get shortcutShift => 'Shift';

  @override
  String get shortcutAlt => 'Alt';

  @override
  String get shortcutMeta => 'Meta';

  @override
  String get loading => 'Loading...';

  @override
  String get errorOccurred => 'Error Occurred';

  @override
  String errorSelectingFile(Object error) {
    return 'An error occurred while selecting the file: $error';
  }

  @override
  String get fileTooLarge => 'File Too Large';

  @override
  String get fileTooLargeMessage =>
      'The selected file exceeds the 10MB size limit.';

  @override
  String get unsupportedFileType => 'Unsupported File Type';

  @override
  String get unsupportedFileTypeMessage =>
      'Only the following file types are supported: TXT, PNG, JPG, GIF, PDF.';

  @override
  String get passwordGeneratorTitle => 'Password Generator';

  @override
  String passwordLengthLabel(Object length) {
    return 'Password Length: $length';
  }

  @override
  String get listViewTooltip => 'Switch to List View';

  @override
  String get gridViewTooltip => 'Switch to Grid View';
}
